name: google_calendar
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  extension_google_sign_in_as_googleapis_auth: ^2.0.2
  firebase_auth: ^2.0.0
  flutter_riverpod: ^0.14.0+3
  freezed_annotation: ^0.14.2
  google_sign_in: ^5.0.4
  googleapis: ^3.0.0
  googleapis_auth: ^1.1.0
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  freezed: ^0.14.2

flutter: null
